/*
 * This file is generated by jOOQ.
 */
package ge.tsu.spring.lecture6.db;


import ge.tsu.spring.lecture6.db.tables.Weather;
import ge.tsu.spring.lecture6.db.tables.records.WeatherRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<WeatherRecord> WEATHER_PKEY = Internal.createUniqueKey(Weather.WEATHER, DSL.name("weather_pkey"), new TableField[] { Weather.WEATHER.ID }, true);
}
