/*
 * This file is generated by jOOQ.
 */
package ge.tsu.spring.lecture6.db;


import ge.tsu.spring.lecture6.db.tables.Weather;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.weather</code>.
     */
    public static final Weather WEATHER = Weather.WEATHER;
}
